### ISSUE TITLE
big empty space

### ISSUE THREAD

**Issue by geekhenno** [GursheeshSingh/creditcard_slider#1]
hello,
thanks for the beautiful package, but there is a big empty space because it starts from index 0 at the center, 
why I can not change the initial start index, or make the slider looping because the empty space in the screen it is to big

**Comment by GursheeshSingh** [comment]
okay 

I will add an initial page parameter 👍🏻

Do you want try out?

**Comment by geekhenno** [comment]
Thanks a lot
Yes please

**Comment by GursheeshSingh** [comment]
I have added initial page on this commit-

https://github.com/GursheeshSingh/creditcard_slider/commit/64a01944ae1e3318a449352ecf3007553aa73d31

You would have to download this version instead of the one on pub.

If it works well for you, I will update the package on pub.

Now you can do-

```
child: CreditCardSlider(
          _creditCards,
          initialPage: 1,
          onCardClicked: (index) {
            print('Clicked at index: $index');
          },
        ),
```

**Comment by GursheeshSingh** [comment]
Let me know if it works well for you

**Comment by geekhenno** [comment]
Thank you so much,
You are the best.
I will try and let you know..

**Comment by geekhenno** [comment]
It works very well
Another suggestion
If you can make the list of cards loop
So when I reach the last index of cards
The next one will be index 0
(repeating)

**Comment by GursheeshSingh** [comment]
Great suggesstion!

Currently, the animation doesn't work once we pass the first list of cards.

I will try it out.

**Comment by geekhenno** [comment]
thanks for your time♥️

**Comment by GursheeshSingh** [comment]
Its done

https://github.com/GursheeshSingh/creditcard_slider/commit/7eebfb0a6b3cd96d502c41bced450eb03cee7c38

You need to specify _**repeatCards to true**_

```
 CreditCardSlider(
         _creditCards,
         repeatCards: true,
         onCardClicked: (index) { 
         print('Clicked at index: $index');
         },
 ),
```

![repeatCards](https://s7.gifyu.com/images/repeatCards.gif)

**Comment by GursheeshSingh** [comment]
![repeatCards](https://user-images.githubusercontent.com/31126864/86387508-e7f3c500-bcb0-11ea-866f-1ecb6465f876.gif)

**Comment by GursheeshSingh** [comment]
https://gifyu.com/image/Qxps

**Comment by GursheeshSingh** [comment]
Let me know if it works for you

Then I will close the issue

**Comment by geekhenno** [comment]
it works very well, thank you so much bro for your time

**Comment by GursheeshSingh** [comment]
Welcome :)

Feel free to contribute!

and thank you for your great suggestions
