### ISSUE TITLE
custmization

### ISSUE THREAD

**Issue by geekhenno** [GursheeshSingh/creditcard_slider#2]
I want to add custom logo please,
there is no customization,
I want to use it in my project

**Comment by GursheeshSingh** [comment]
Do you want to add custom bank logo?

**Comment by geekhenno** [comment]
Yes please,,
I want use your package, I like it so much

**Comment by GursheeshSingh** [comment]
Thank you!

You can add a custom company logo:

https://github.com/GursheeshSingh/creditcard_slider#creating-a-custom-company-card

Make sure you set the right size to avoid overflow

**Comment by geekhenno** [comment]
Thank you so much bro
