### ISSUE TITLE
repeated pages

### ISSUE THREAD

**Issue by geekhenno** [GursheeshSingh/creditcard_slider#3]
good evening,
the repeated work just from one way, down to up, but from up to down not work

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25689733/86529959-658c2080-bebd-11ea-868a-d5ec25f1ef81.gif)

**Comment by geekhenno** [comment]
in StackOverflow they said we can use this package 
https://pub.dev/packages/infinity_page_view

**Comment by GursheeshSingh** [comment]
I will check this out tonight.

**But having dependency on another project wouldn't be good.**

It should not be that hard

I will try to find a solution and see how this works

**Comment by geekhenno** [comment]
Thanks a lot♥️

**Comment by GursheeshSingh** [comment]
I have updated the repo with repeat available in both directions

Instead of using `repeatCards: true`

Now use

```
repeatCards: RepeatCards.DOWN //for down repeat only

repeatCards: RepeatCards.BOTH_DIRECTIONS //for both directions

```

Let me know if it works properly

**Comment by geekhenno** [comment]
Thank you so much bro.
It works very well♥️🔥😍😍

**Comment by GursheeshSingh** [comment]
Welcome :)
