### ISSUE TITLE
card page

### ISSUE THREAD

**Issue by geekhenno** [GursheeshSingh/creditcard_slider#5]
![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2020-07-06 at 14 23 29](https://user-images.githubusercontent.com/25689733/86588382-4613f700-bf94-11ea-891a-00b52ec10bd3.png)

the cards look like this at first-time page loaded, it seems no cards selected

**Comment by geekhenno** [comment]
the last pull request fixed this problem.
if you can take a look.
thanks a lot.

**Comment by GursheeshSingh** [comment]
I know this bug, it seems to be just there for a split second.

It only happens if we specify initialPage

I will look into it.

**Comment by GursheeshSingh** [comment]
Let me know if this fixes.
According to me its fixed.
